name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the Repository
        uses: actions/checkout@v3
      - name: Building the Project
        run: npm ci && npm run build
      - name: Launch Firebase Preview
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: hosting
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CADS_WEBSITE_MERRIMACK_DEV }}'
          projectId: cads-website-merrimack-dev
          channelId: main
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
      - name: Echo the URL
        run: |
          urls="${{ steps.hosting.outputs.urls }}"
          first_url="${urls[0]}"
          echo "First URL is $first_url"
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test -u ${{steps.hosting.outputs.urls[0]}}
